apiVersion: v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: siffreins
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-deployment
          image: mongodb/mongodb-community-server:latest
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-pv
              mountPath: /data/db
          resources:
            limits:
              cpu: {{ .Values.resources.db.limits.cpu }}
              memory: {{ .Values.resources.db.limits.memory }}
            requests:
              cpu: {{ .Values.resources.db.requests.cpu }}
              memory: {{ .Values.resources.db.requests.memory }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_DATABASE
            - name: MONGODB_DATADIR
              value: /data/db
      volumes:
        - name: mongodb-pv
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: siffreins
spec:
  selector:
    app: mongodb
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
