apiVersion: v1
kind: ConfigMap
metadata:
  name: webdb-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.db.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.db.password }}
  MONGO_INITDB_DATABASE: {{ .Values.db.database }}
