apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: siffreins
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-statefulset
          image: mongodb/mongodb-community-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: {{ .Values.resources.db.limits.cpu }}
              memory: {{ .Values.resources.db.limits.memory }}
            requests:
              cpu: {{ .Values.resources.db.requests.cpu }}
              memory: {{ .Values.resources.db.requests.memory }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_DATABASE
            - name: MONGODB_DATADIR
              value: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: siffreins
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
