apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: webdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb-deployment
          image: siffreinsg/net4255_webdb:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.resources.webdb.limits.cpu }}
              memory: {{ .Values.resources.webdb.limits.memory }}
            requests:
              cpu: {{ .Values.resources.webdb.requests.cpu }}
              memory: {{ .Values.resources.webdb.requests.memory }}
          env:
            - name: MONGODB_HOSTNAME
              value: mongodb-service
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_DATABASE
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
