db:
  username: root
  password: pass
  database: webdb

webdb:
  host: webdb.siffreins.net4255.luxbulb.org

webnodb:
  host: webnodb.siffreins.net4255.luxbulb.org

resources:
  db:
    storage: "100M"
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  webdb:
    limits:
      memory: "200M"
      cpu: "500m"
    requests:
      memory: "100M"
      cpu: "100m"
  webnodb:
    limits:
      memory: "200M"
      cpu: "500m"
    requests:
      memory: "100M"
      cpu: "100m"
