apiVersion: v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: siffreins
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-deployment
          image: mongodb/mongodb-community-server:latest
          imagePullPolicy: onlyIfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-pv
              mountPath: /data/db
          resources:
            limits:
              memory: "200M"
              cpu: "500m"
            requests:
              memory: "100M"
              cpu: "100m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass
            - name: MONGO_INITDB_DATABASE
              value: webdb
            - name: MONGODB_DATADIR
              value: /data/db
      volumes:
        - name: mongodb-pv
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: siffreins
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
