apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: siffreins
spec:
  type: ClusterIP
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
