apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:latest
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          ports:
          - name: mongodb
            containerPort: 27017
          volumeMounts:
          - name: dbdata
            mountPath: /data/db
          resources:
            limits:
              cpu: {{ .Values.resources.db.limits.cpu }}
              memory: {{ .Values.resources.db.limits.memory }}
            requests:
              cpu: {{ .Values.resources.db.requests.cpu }}
              memory: {{ .Values.resources.db.requests.memory }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: webdb-configmap
                  key: MONGO_INITDB_DATABASE
            - name: MONGODB_DATADIR
              value: /data/db
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.resources.db.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
