apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: webnodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
        - name: webnodb-deployment
          image: siffreinsg/net4255_webnodb:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.resources.webnodb.limits.cpu }}
              memory: {{ .Values.resources.webnodb.limits.memory }}
            requests:
              cpu: {{ .Values.resources.webnodb.requests.cpu }}
              memory: {{ .Values.resources.webnodb.requests.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
